on:
  push:
    branches:
    - '**'
jobs:
  build_docs:
    name: Build the documentation site
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.111.2
      GCLOUD_VERSION: 458.0.1-linux-x86_64
      BUCKET: docs-prod-learn-redis-com
      BUCKET_SERVICE_ACCOUNT: ${{ secrets.BUCKET_DOCUMENTATION_SA_PROD }}
      BUCKET_SECRET: ${{ secrets.BUCKET_DOCUMENTATION_PROD }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT_PROD }}
    steps:
    - name: Start
      run: echo "The name of the branch is ${{ github.ref }} on ${{ github.repository }}"
    - name: Install Hugo
      run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name: Check the branch out
      uses: actions/checkout@v4
    - name: List repository files
      run: ls ${{ github.workspace }}
    - name: Install dependencies and run Hugo
      run: make all
    - name: List client examples
      run: ls "${{ github.workspace }}/examples"
    - name: List files to be published
      run: ls "${{ github.workspace }}/public"    
    - name: Install the Google Cloud CLI
      run: |
          wget -O ${{ github.workspace }}/google-cloud-cli.tar.gz "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-$GCLOUD_VERSION.tar.gz" \
          && tar -xvf google-cloud-cli.tar.gz -C ${{ github.workspace }}\
          && ${{ github.workspace }}/google-cloud-sdk/install.sh --quiet
    - name: Prepare bucket authentication
      run: echo $BUCKET_SECRET | base64 --decode > service_account.json && ls -a service_account.json
    - name: Authenticate to the bucket
      run: |
          ./google-cloud-sdk/bin/gcloud auth activate-service-account $BUCKET_SERVICE_ACCOUNT --key-file=./service_account.json --project=$GCP_PROJECT \
          && ./google-cloud-sdk/bin/gcloud auth list
    - name: Sync the branch to the bucket
      run: |
          if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "latest" ]]
          then
            bucket_path=${{ github.ref_name }}
          elif [[ "${{ endsWith(github.ref_name, '-build') }}" == "true" ]]
          then
            bucket_path=`echo ${{ github.ref_name }} | sed 's/-build$//'`
          else
            bucket_path="/staging/${{ github.ref_name }}"
          fi \
          && ./google-cloud-sdk/bin/gsutil rsync -c -j html -d -r ${{ github.workspace }}/public gs://$BUCKET/$bucket_path
    - name: End
      run: echo "This job's status is ${{ job.status }}."
