
on:
  push:
    branches:
    - '**'
jobs:
  test_gcs:
    name: Test Google Cloud Storage access
    runs-on: ubuntu-latest
    env:
      GCLOUD_VERSION: 458.0.1-linux-x86_64
      BUCKET_SECRET: ${{ secrets.BUCKET_DOCUMENTATION_PROD }} 
    steps:
    - name: Start
      run: echo "The name of the branch is ${{ github.ref }} on ${{ github.repository }}"
    - name: Fetch the credentails
      run: echo $BUCKET_SECRET | base64 --decode > service_account.json && ls -a service_account.json
    - name: Install the Google Cloud CLI
      run: |
          wget -O ${{ github.runner_temp }}/google-cloud-cli.tar.gz "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-$GCLOUD_VERSION.tar.gz" \
          && tar -xvf google-cloud-cli.tar.gz -C ${{ github.runner_temp }}\
          && ${{ github.runner_temp }}/google-cloud-sdk/install.sh --disable-prompts
    - name: End
      run: echo "This job's status is ${{ job.status }}."
   
